version: "3.1"
services:
  data-cloning-service:
    container_name: data-cloning
    build:
      context: ./data-cloning 
      dockerfile: ./dockerfile
    ports:
      - 3004:3004
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_DISABLE=True
    volumes:
    - ./Data_files:/data/Runs

  data-socket-service:
    container_name: data-socket
    build:
      context: ./data-socket
      dockerfile: ./dockerfile
    ports:
      - 3003:3003
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_DISABLE=True

  redis:
    container_name: redis-db
    image: redis:7.0.5
    ports:
      - 6379:6379
